############################################################################
# pnut-os/src/lib/Makefile
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Mateusz Pianka
#
############################################################################

include $(APPDIR)/Make.defs

# libpnut, built into nuttx-apps' library with the programs

CSRCS = clock.c log.c loop.c module.c pool.c timer.c worker.c

include $(APPDIR)/Application.mk
