############################################################################
# pnut-os/src/lib/Makefile
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Mateusz Pianka
#
############################################################################

include $(APPDIR)/Make.defs

# libpnut, built into nuttx-apps' library with the programs

CSRCS  = client.c clock.c conn.c log.c loop.c module.c msg.c pool.c
CSRCS += service.c timer.c worker.c

include $(APPDIR)/Application.mk
