############################################################################
# pnut-os/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Mateusz Pianka
#
############################################################################

# nuttx-apps builds this directory as apps/external, a link the top-level
# Makefile makes.  Each directory below with a Makefile is built, and its
# Kconfig joins the "pnut-os" menu.

MENUDESC = "pnut-os"

include $(APPDIR)/Directory.mk
